2022-12-02 03:33:40,470 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python3.10/dist-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/media/hossam/C858381B58380B28/microblog/app/routes.py", line 70, in reset_password_request
    send_password_reset_email(user)
  File "/media/hossam/C858381B58380B28/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/media/hossam/C858381B58380B28/microblog/app/models.py", line 71, in get_reset_password_token
    exp = time() + 600
TypeError: unsupported operand type(s) for +: 'datetime.time' and 'int'
2022-12-02 03:34:48,465 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:46]
2022-12-02 03:34:52,062 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python3.10/dist-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/media/hossam/C858381B58380B28/microblog/app/routes.py", line 70, in reset_password_request
    send_password_reset_email(user)
  File "/media/hossam/C858381B58380B28/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/media/hossam/C858381B58380B28/microblog/app/models.py", line 71, in get_reset_password_token
    exp = datetime.timedelta(seconds=10)
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
2022-12-02 03:35:09,873 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:46]
2022-12-02 03:35:13,709 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python3.10/dist-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/media/hossam/C858381B58380B28/microblog/app/routes.py", line 70, in reset_password_request
    send_password_reset_email(user)
  File "/media/hossam/C858381B58380B28/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/media/hossam/C858381B58380B28/microblog/app/models.py", line 74, in get_reset_password_token
    {'reset_password': self.id, "exp": datetime.now(tz=timezone.utc) + timedelta(seconds=30)}, app.Config['SECRET_KEY'],algorithm='HS256')
TypeError: 'type' object is not subscriptable
2022-12-02 03:35:39,473 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:46]
2022-12-02 03:35:53,347 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python3.10/dist-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/media/hossam/C858381B58380B28/microblog/app/routes.py", line 70, in reset_password_request
    send_password_reset_email(user)
  File "/media/hossam/C858381B58380B28/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/media/hossam/C858381B58380B28/microblog/app/models.py", line 72, in get_reset_password_token
    {'reset_password': self.id, "exp": timedelta(seconds=expires_in)}, app.Config['SECRET_KEY'],algorithm='HS256')
TypeError: 'type' object is not subscriptable
2022-12-02 03:36:29,720 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:46]
2022-12-02 03:36:34,213 ERROR: Exception on /reset_password_request [POST] [in /usr/local/lib/python3.10/dist-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/media/hossam/C858381B58380B28/microblog/app/routes.py", line 70, in reset_password_request
    send_password_reset_email(user)
  File "/media/hossam/C858381B58380B28/microblog/app/email.py", line 14, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/media/hossam/C858381B58380B28/microblog/app/models.py", line 72, in get_reset_password_token
    {'reset_password': self.id, "exp": timedelta(seconds=30)}, app.Config['SECRET_KEY'],algorithm='HS256')
TypeError: 'type' object is not subscriptable
2022-12-03 09:30:24,512 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:48]
2022-12-03 10:43:53,017 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:50]
2022-12-03 10:45:52,128 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:50]
2022-12-03 10:56:55,599 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:50]
2022-12-03 10:57:00,043 INFO: Microblog startup [in /media/hossam/C858381B58380B28/microblog/app/__init__.py:50]
